export const GET_SIGNIN = 'GET_SIGNIN';
export const GET_SIGNIN_ATTEMPT = 'GET_SIGNIN_ATTEMPT';
export const GET_SIGNIN_SUCCESS = 'GET_SIGNIN_SUCCESS';
export const GET_SIGNIN_FAIL = 'GET_SIGNIN_FAIL';
